name: 
caption: John Guardado
author: jguardado39
baseurl: ""
description: John's Project Hub
github: http://www.github.com/jguardado39
twitter: https://twitter.com/jguardado39
facebook: https://www.facebook.com/jguardado39
linkedin: https://www.linkedin.com/in/john-guardado-4a673a39/
email: jguardado39@gmail.com
location: Berkeley
disqus: jguardado39
##SEO
social: 
  name:
  links:
    - https://twitter.com/jguardado39
    - http://www.github.com/jguardado39
    - https://www.linkedin.com/in/john-guardado-4a673a39/
webmaster_verifications:
  google: oa8y9MR5B22kp07Kg_h0C5ZHqkosnQ6zeNf8x7CGP_w
  bing: CDC9B5FE4D8275A97E431F68295D6016

url: https://jguardado39.github.io/


gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

##Make sure to edit the above fields, especially for disqus.
permalink: /:categories/:title.html

##highlighter: rouge ##pygments --> No Longer In Use
markdown: kramdown ##redcarpet -->No Longer in Use
##redcarpet: --> Not required
##  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
